src/main.rs

resolves https://github.com/flashbots/rollup-boost/issues/19

Add optional builder jwt token param

---

src/proxy.rs
src/server.rs

Resolves https://github.com/flashbots/rollup-boost/issues/14

Proxy eth_sendRawTransaction to builder

---

.dockerignore
Dockerfile
src/main.rs
src/server.rs

Resolves https://github.com/flashbots/rollup-boost/issues/32

Add builder url to logs

---

README.md

Also the diagram should change from `sidecar` to `rollup-boost` to be more explicit

Sidecar disambiguation

---

Cargo.lock
Cargo.toml
src/main.rs
src/server.rs

This PR fixes an issue in which `op-geth` sends some extra (useless) params as part of the FCU response that could not be parsed with `alloy` since it did not allow unknown fields.
Fix in alloy https://github.com/alloy-rs/alloy/pull/1740

Update alloy to fix op-geth extra payload fields

---

src/server.rs

This PR adds payload ID mapping functionality to track and map between local and external payload IDs when interacting with the builder node. This ensures proper correlation between payloads across different nodes.
Key changes:
- Added `local_to_external_payload_ids` cache to `PayloadTraceContext` to store mappings
- Added methods to store and retrieve payload ID mappings
- Updated `get_payload_v3` to use external payload ID when requesting from builder
- Added payload ID mapping in `fork_choice_updated_v3` response handling
- Added logging improvements to track both local and external payload IDs
The changes help maintain proper tracing and correlation between local execution engine payloads and external builder payloads, improving debuggability and reliability of the system.
fixes #46

chore: local -> external builder mapping

---

src/integration/mod.rs
src/integration/service_rb.rs
src/integration/service_reth.rs

Stop the integration test if a service exists during initialization. Before, we would wait for the timeout of the poll_logs method but that can be slow and it does not give you useful information to know why the process did not start.

Stop integration if service stopped during init

---

src/integration/service_rb.rs
src/main.rs

This PR enables boost sync by default since for lower block times (<300ms) it is a requirement to receive the latest block as fast as possible. The PR changes the flag `--boost-sync` that enabled boost sync with a new flag `--no-boost-sync` which disables it if not required.

Enable boost-sync by default

---

Cargo.lock
Cargo.toml
src/integration/integration_test.rs
src/integration/mod.rs
src/integration/proxy.rs
src/server.rs

This PR adds a proxy in between Rollup-boost and the builder and adds two tests:
- One that simulates latency between Rollup-boost and the builder.
- One that changes the state root from the payload returned by the builder. Rollup-boost has to detect it and return the L2 block.

Add a proxy in between Rollup-boost + Rbuilder and simulate latencies

---

Cargo.lock
Cargo.toml
src/auth_layer.rs
src/client.rs
src/integration/mod.rs
src/main.rs
src/proxy.rs
src/server.rs

This PR removes the three Reth dependencies we had since we can replace them with dependencies from alloy and copying a couple of simple functions from Reth.

Remove reth deps

---

Makefile

makefile for build, lint, fmt commands

Add makefile for rollup boost

---

Cargo.lock
Cargo.toml
src/main.rs
src/proxy.rs

Adds TLS compatibility to client in the proxy. 
This is important as the JWT can be sniffed out of the headers in non `https` connections with the builder. These changes are backwards compatible with `http`, but now allow `rollup-boost` to connect to the builder over the auth API in the proxy through TLS.

feat: add TLS support in Proxy client

---

Cargo.lock
Cargo.toml

Add native-tls to `tokio-tungstenite` to support wss

Add wss support

---

src/server.rs

https://github.com/flashbots/rollup-boost/issues/125
Previous code was assuming the local execution would be in sync

Fix panic on local payload id is none

---

src/main.rs
src/server.rs

Add a CLI argument `--execution-mode` to allow users to set the execution mode on startup. Currently when deploying a new sequencer, we:
1. Start a new node
2. Restore a snapshot
3. Sync the node top tip
4. Do a handover from the old sequencer to the new
In this flow, it would be ideal to start rollup boost on the new node with exeuciton-mode=disabled, then on the handover (step 4) set the execution mode to enabled.

chore: argument to set execution 

---

Cargo.lock
Cargo.toml
src/proxy.rs

Resolves https://github.com/flashbots/rollup-boost/issues/130. 
`http_helpers::read_body` asserts the response is in json when EL responses can be gzipped. This tries to unzip the payload async and record the relevant metrics

Fix error reading body when forwarding calls

---

docs/load-testing-acceptance-criteria-template.md

Template for Load Testing Acceptance Criteria to fill out whenever load testing and upgrading a block builder on a L2 network.

Docs: Load Testing Acceptance Criteria

---

Cargo.lock
Cargo.toml
src/bin/main.rs
src/cli.rs
src/client/http.rs
src/client/rpc.rs
src/health.rs
src/lib.rs
src/metrics.rs
src/proxy.rs
src/server.rs
src/tracing.rs

Refactors rollup-boost into a lib/bin such that it can be used as a dependency of other crates.
This PR also reduces the binary size by making dependencies behind feature flags optional, and removing all unused dependencies.

feat: expose rollup-boost library

---

Cargo.lock
Cargo.toml

Reth 1.3.11

---

src/client/http.rs
src/server.rs
src/tracing.rs

previously because of metrics change, broke compatibility with partners who were alerting on those metrics

Maintain metrics backwards compatibility

---

src/client/rpc.rs
src/proxy.rs
src/server.rs
src/tracing.rs

Adds a few metrics, also updates loopback IP in necessary places.
```
rollup_boost_error{code="-38001",span_kind="Client",status="error"} 1
rollup_boost_block_building_gas_delta{payload_source="builder",span_kind="Server",status="unset",quantile="0"} 0
...
rollup_boost_block_building_tx_count_delta_count{payload_source="builder",span_kind="Server",status="unset"} 1
```

metrics updates

---

tests/common/mod.rs

This PR removes an extra log line in the integration tests which was appending to `rollup_boost.log` the logs from all the extra services.

Remove extra log from rollup_boost.log

---

.github/workflows/kurtosis_integration.yml
scripts/ci/kurtosis-params.yaml

Think the issue was actually in `optimism-package` fixed [here](https://github.com/ethpandaops/optimism-package/commit/c79d15eb9a20355d33d564aa52318a7b25fb60f4)
But this is a more reliable workflow anyways.

chore: change ci to k8s for reliability

---

src/proxy.rs

Refactors `ProxyService::call` to simplify the request handling logic. Behavior is unchanged.
The updated flow is as follows:
- If it's an engine API method, send to the inner Rollup Boost server
- If it's a forwardable method, send to both the builder and the default execution client
- Otherwise,  send to the default execution client

chore: simplify `ProxyService::call()` logic

---

src/server.rs

This PR adds a log to print the specific type of FCU call and whether the txpool is enabled for the one that triggers block building.
To give some extra context, during the block building lifecycle there are two FCU calls, one for block building and one after the block has been included on chain. This logs helps to differentiate both cases.

Add log for fcu

---

src/debug_api.rs
src/server.rs

Fixes #196 
Changes made:
- Removed `Fallback` mode from `ExecutionMode`
- `DryRun` mode will get both `l2_payload` and `builder_payload`, but will always send the `l2_payload`. This was different previously where in DryRun, the call to `builder_payload` would return an error.

feat: simplify ExecutionMode

---

src/client/auth.rs

As per the [spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md#jwt-claims) this will give a token a vailidity of 60 seconds. Prior to this change the validity would have been 120 seconds.

fix(auth): use only current timestamp for auth

---

tests/common/mod.rs
tests/fcu_avalanche_with_delay.rs
tests/fcu_no_block_time_delay.rs

Add a test to ensure a FCU call without block delay can be built by the builder

---

.github/workflows/kurtosis_integration.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/websocket-proxy-ci.yaml

The `actions-rs/toolchain` Github action has been archived. Update to a maintained one.

chore: update Rust Ci action

---

src/server.rs

This PR updates the builder health check logic to avoid degrading health status during `ExecutionMode::DryRun`. Currently, a builder failure during `DryRun causes the health to be reported as `Partial` triggering sequencer failover. With this change, dry run failures are ignored for health reporting purposes.

fix: skip health status update during `ExecutionMode::DryRun`

---

crates/websocket-proxy/src/auth.rs
crates/websocket-proxy/src/integration.rs
crates/websocket-proxy/src/main.rs
crates/websocket-proxy/src/metrics.rs
crates/websocket-proxy/src/server.rs

Closes https://github.com/flashbots/rollup-boost/issues/258, adds an authenticated endpoint for allowing clients to connect to the websocket proxy. This PR is a modified version of https://github.com/base/flashblocks-websocket-proxy/pull/11, with the comments addresses.

websocket proxy: Add authenticated endpoint settings

---

crates/websocket-proxy/src/metrics.rs
crates/websocket-proxy/src/registry.rs

we want to disconnect clients who are receiving packets but not active - could be due to device going to sleep, browser tab going to sleep, slow code in message processing on client side, etc. 
previously attempted to solve via adding ping/pong between ws proxy and downstream clients. but we realized that just changing the behaviour of what happens when clients start lagging has the same effect, and more responsive. 
we've noticed on base sepolia that lagging clients typically do not benefit from a resubscription and continue to remain lagging, indicative of an issue on their end. looking at lag metrics right now, a single client on average causes the lag event to trigger 40-50 times, i.e. ~8-10seconds. the worst offenders go for 30+ seconds. 
we'd rather disconnect them when they start …

websocket proxy: disconnect downstream client if lagging

---

crates/rollup-boost/src/server.rs
crates/rollup-boost/src/tests/common/services/rollup_boost.rs
crates/rollup-boost/src/tracing.rs

Resolves https://github.com/flashbots/rollup-boost/issues/253. Removed the `has_attributes` since it was not being included in the span attributes and unused

Add builder has payload attribute to metrics

---

crates/rollup-boost/src/flashblocks/inbound.rs
crates/rollup-boost/src/flashblocks/service.rs
crates/websocket-proxy/src/subscriber.rs

Run make fmt
Added check to ensure that we returning block constructed from flashblock
Removed double lock - this changed behavior a bit, but even if into_envelope fails we would have FlashblockBuilder::new() in best_payload

Fix FB race

---

Cargo.lock
crates/websocket-proxy/Cargo.toml
crates/websocket-proxy/README.md
crates/websocket-proxy/src/client.rs
crates/websocket-proxy/src/integration.rs
crates/websocket-proxy/src/main.rs
crates/websocket-proxy/src/registry.rs

The Websocket Proxy serves many downstream clients, and the raw JSON payload of the Flashblock stream adds up pretty quickly. Estimated monthly egress is quite high.
This PR introduces Brotli compression on the proxy level, giving us an average improvement of ~5.5-6x on the payload size tested against Base Sepolia. On Base Mainnet where blocks are larger, the difference is likely going to be even larger. 
Downstream clients (like Flashblocks aware preconf nodes) and direct WS consumers will need to implement decompression of the message before parsing it as JSON.

ws proxy: brotli compress each message from upstream before sending downstream

---

crates/rollup-boost/src/client/rpc.rs

Uses `User-Agent` key in Rollup-boost Http call header that includes the version.

Use User-agent in RB header

---

crates/websocket-proxy/src/main.rs
crates/websocket-proxy/src/rate_limit.rs

Migrate from a global connection limit shared across all instances to a per instance limit. Previously you could have had two instances, one with 99 connections and one with 1 connection. If a new connection was opening to the instance with 1 connection, it would have been rate limited.
The new state of rate limiting when redis is enabled is:
1. Per IP rate limiting across instances / stored in Redis
2. Instance rate limiting (in memory sempahore)
3. Global rate limiting can be controlled by number of instanaces * instance rate limit

chore: overall websocket limits should be per instance

---

Cargo.lock
Cargo.toml
crates/rollup-boost/Cargo.toml
crates/rollup-boost/src/flashblocks/inbound.rs
crates/rollup-boost/src/flashblocks/metrics.rs
crates/rollup-boost/src/flashblocks/mod.rs
crates/rollup-boost/src/flashblocks/service.rs
crates/websocket-proxy/Cargo.toml

This PR adds an initial batch of metrics for flashblocks.

Initial batch of metrics for flashblocks service

---

crates/rollup-boost/src/flashblocks/inbound.rs
crates/rollup-boost/src/flashblocks/metrics.rs

This PR adds a ping/pong system over the Rollup-boost <-> Builder connection. The context of this PR is in #304.
The inbound websocket service will send ping messages to the builder if after some time interval x has not received any message from the builder. After sending the ping message, it will wait another n time duration to receive the pong message back.
The test still needs more work.

Rollup-boost uses ping/pong to test the connection is open

---

crates/rollup-boost/Cargo.toml
crates/rollup-boost/src/flashblocks/inbound.rs

This PR fixes two issues with Flashblocks ping/pong protocol:
- The ping interval and the pong timeout have the same time duration (500ms) so it is really easy to timeout.
- The ping routine was not cleaned after a ping timeout so the websocket connection stays open and it does not get dropped.

Fix flashblocks ping/pong intervals

---

Dockerfile
Justfile

Closes #338. The docker in debug mode takes 5m to build vs release mode that takes 11m.

Parametrise Dockerfile to build debug binaries

---

Justfile

There is an ongoing refactor of the Optimism Kurtosis package and we have already updated at least in three occasions the spec. Right now, with the latest changes the chain does not advance, ref https://github.com/ethpandaops/optimism-package/issues/349.
This PR pins for the short term the Kurtosis spec to a version that is funtional.

Pin Kurtosis

---

Cargo.lock
Cargo.toml
crates/flashblocks-rpc/Cargo.toml
crates/flashblocks-rpc/src/cache.rs
crates/flashblocks-rpc/src/flashblocks.rs
crates/flashblocks-rpc/src/lib.rs
crates/flashblocks-rpc/src/rpc.rs
crates/flashblocks-rpc/src/tests/assets/genesis.json
crates/flashblocks-rpc/src/tests/mod.rs

This PR adds the initial scaffolding for the e2e test for the Flashblocks RPC and a few e2e tests to cover the `eth_getBlockByNumber`, `eth_getBalance` and `eth_getTransactionReceipt` endpoints. There are still more tests to finish that are not being covered as part of this PR.

E2E tests for flashblocks RPC

---

crates/websocket-proxy/src/main.rs
crates/websocket-proxy/src/subscriber.rs

Add ping/pong for upstream connections (see https://github.com/flashbots/rollup-boost/issues/322). I'll add the equivalent for downstream clients in a separate PR

fix: ping/pong upstream server

---

.github/workflows/release.yml
crates/rollup-boost/src/flashblocks/service.rs

We encountered a problem that if builder does not receive getPayload it will not preserve current executed block to the cache. This change fix this, but adds a little bit of latency in the hot path of flashblocks

Always send get_payload to builder

---

Cargo.lock
Cargo.toml
Dockerfile
Justfile
README.md
crates/flashblocks-rpc/Cargo.toml
crates/flashblocks-rpc/src/cache.rs
crates/rollup-boost/Cargo.toml
crates/websocket-proxy/Dockerfile
docs/local-devnet.md
scripts/ci/kurtosis-params.yaml

Upgrade to reth 1.7.0 which was breaking kurtosis

Upgrade deps to reth 1.7.0 and fix kurtosis
