flashbots/rollup-boost

.env.example, Cargo.lock, Cargo.toml, README.md, src/error.rs, src/main.rs, src/proxy.rs, src/server.rs
resolves https://github.com/flashbots/rollup-boost/issues/6
=> Multiplex engine calls to builder

.github/workflows/release.yml
=> use warp runner for release action

src/proxy.rs
Resolves https://github.com/flashbots/rollup-boost/issues/28
=> Add health check endpoint

Cargo.lock, Cargo.toml, Dockerfile, src/main.rs, src/server.rs
WIP, waiting for issues to resolve as described in https://github.com/flashbots/rollup-boost/issues/25. 
Jaeger tracing UI:
=> Add Tracing

src/main.rs
Resolves https://github.com/flashbots/rollup-boost/issues/31
=> Disable coloured logging by default

src/main.rs
This PR adds default values for `l2-url` (default authrpc address).
=> Add defaults for jwt token and l2 url

src/main.rs, src/proxy.rs
https://github.com/flashbots/rollup-boost/issues/49
=> Separate metrics server from rpc server

.env.example, src/main.rs
https://github.com/flashbots/rollup-boost/issues/51
=> Add log format json in args

src/main.rs
Implements graceful shutdown upon SIGINT or SIGTERM using 
fixes #50 
TODO - testing
=> chore: graceful shutdown

README.md
This PR updates the README to reflect changes to the cli args introduced in #69
=> docs: Update README to reflect changes to cli args

src/metrics.rs, src/server.rs
This PR adds latency metrics for the engine api methods.
=> Add latency metrics

src/server.rs
With this PR we do not query get_payload from block builder if we know that it is not building the block during no_tx_pool request calls. Before, this showed as errors in the logs as the builder did not have any reference to the payload.
=> Do not query builder if it is not building the block

src/server.rs
=> feat: Remove PayloadID field in FCU request if not doing block building

src/metrics.rs, src/server.rs
=> Add metrics for the creator of the block

src/main.rs
=> Fix Prometheus metrics server

.github/workflows/kurtosis_integration.yml, scripts/ci/kurtosis-params.yaml, scripts/ci/kurtosis.sh
This PR adds a CI check that validates that Rollup-boost works in Kurtosis.
Closes #113
=> Add kurtosis ci check

README.md, RELEASE.md, docs/running-rollup-boost.md
Resolves https://github.com/flashbots/rollup-boost/issues/86 https://github.com/flashbots/rollup-boost/issues/88 https://github.com/flashbots/rollup-boost/issues/89
https://github.com/flashbots/rollup-boost/issues/90 not yet in this PR, future work as follow up
Also adds a small change to the debug api to convert the enum to snake case
=> Add production docs

src/server.rs
Remove verbose println! on each FCU call
=> chore: remove verbose println

Cargo.lock, Cargo.toml, src/flashblocks/service.rs
Bump alloy & op alloy deps. Required for https://github.com/flashbots/rbuilder/pull/507
=> deps: alloy 0.12.5

Cargo.lock, Cargo.toml
=> deps: alloy 0.12.6

RELEASE.md, docs/running-rollup-boost.md, src/client/rpc.rs
=> chore(docs): Fix typos

.dockerignore, src/debug_api.rs, src/server.rs
=> feat: add fallback execution mode

src/server.rs
Partially solves https://github.com/flashbots/rollup-boost/issues/193 for when the fcu was not sent to the builder as no tx pool was false
=> Fix unknown payload for get payload with no txpool

scripts/ci/stress.sh
This PR updates the flags for Contender to fix the CI
=> fix: update contender flags

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/feature.md
This PR introduces issue templates for bugs, docs and new feature suggestions.
=> feat: issue templates for bug, docs, feature

docs/local-devnet.md
fixes https://github.com/flashbots/rollup-boost/issues/212
=> docs: update local-devnet.md

docs/running-rollup-boost.md
=> docs:Update running-rollup-boost.md

src/health.rs, src/server.rs
Remove items from trace context even when execution mode is disabled.
=> fix: trace context cache eviction

src/server.rs
Also splits `test_server` into individual tests since this change allows us to run each test concurrently
=> chore: bind services to random ports in tests

.github/workflows/kurtosis_integration.yml, README.md, scripts/ci/stress.sh
closes #256 
Having a hard time running kurtosis on my machine, though, so I haven't been able to test locally.
=> use contender via docker in ci

docs/reorgs.md
=> Add doc on reorgs

.github/workflows/build.yml
=> Release nightly docker images for Rollup-boost

crates/rollup-boost/src/flashblocks/inbound.rs, crates/rollup-boost/src/flashblocks/primitives.rs
=> Test websocket reconnect

docs/flashblocks.md
=> Add docs on how to run Flashblocks

crates/rollup-boost/src/flashblocks/service.rs
=> Add Flashblocks builder test

crates/rollup-boost/src/flashblocks/metrics.rs, crates/rollup-boost/src/flashblocks/service.rs
Add counter metrics to use it with rate/irate
Change flashblocks_used to gauge
Add flashblocks_missing to see distribution, use atomic with max to see how much fbs we have missed
=> Improve FB metrics even more

crates/websocket-proxy/src/auth.rs, crates/websocket-proxy/src/main.rs, crates/websocket-proxy/src/rate_limit.rs, crates/websocket-proxy/src/server.rs, crates/websocket-proxy/tests/integration.rs
rebase of https://github.com/flashbots/rollup-boost/pull/314
=> Rate limit per app/api-key on the authed endpoint
